# On push to main, aggregate a release PR.
# If the release PR is merged and a tag created, a new image will be pushed to Dockerhub.
name: Main

on:
  push:
    branches: [ "main" ]

env:
  REGISTRY: docker.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  release:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      # Release
      - uses: actions/checkout@v4
      - id: release
        uses: googleapis/release-please-action@v4
      # Publish
      - if: ${{ steps.release.outputs.release_created }}
        uses: docker/setup-buildx-action@v3
      - if: ${{ steps.release.outputs.release_created }}
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: 'thequeenisdead'
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      - if: ${{ steps.release.outputs.release_created }}
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            # set latest tag for default branch: https://github.com/docker/metadata-action#latest-tag
            type=raw,value=latest,enable={{is_default_branch}}
      - if: ${{ steps.release.outputs.release_created }}
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
